### PR TITLE
Wb 9-Blog top nav

### PR DESCRIPTION
**Pull request by t34Virus**

### CODE REVIEW

**Comment by jasonrsavino** [comment]
@treindle two things:
1. I do not see the /app/config/sculpin_kernel.yml file in this request
2. there are merge conflicts, please pull the master branch into the WB-9 branch and resolve before pushing the changes

**Comment by t34Virus** [comment]
Reverted back to previous, working commit because collaborative code broke other features.

**Comment by drnikko** [comment]
@treindle The comment from Jason above still applies
"I do not see the /app/config/sculpin_kernel.yml file in this request"

**Comment by t34Virus** [comment]
No changes needed to be made to that file.  He's talking about a test branch that was created to add this branch's feature but in the end, it wasn't needed.

**Comment by drnikko** [comment]
Cool @jasonrsavino I'll let you approve this one then.

**Pull request merged**
